//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraRutasTransportes
    {
        public CabeceraRutasTransportes()
        {
            this.RutasTransportes = new HashSet<RutasTransportes>();
            this.DomiciliosPersonal = new HashSet<DomiciliosPersonal>();
            this.DomiciliosPersonal1 = new HashSet<DomiciliosPersonal>();
        }
    
        public long Id { get; set; }
        public string Empresa { get; set; }
        public string Linea { get; set; }
        public string Turno { get; set; }
        public string TipoUnidad { get; set; }
        public string HorariosSalida { get; set; }
        public string HorariosLlegada { get; set; }
        public string TipoRecorrido { get; set; }
        public string TipoTurno { get; set; }
        public Nullable<decimal> Km { get; set; }
        public string DetalleRuta { get; set; }
        public Nullable<int> Capacidad { get; set; }
    
        public virtual ICollection<RutasTransportes> RutasTransportes { get; set; }
        public virtual ICollection<DomiciliosPersonal> DomiciliosPersonal { get; set; }
        public virtual ICollection<DomiciliosPersonal> DomiciliosPersonal1 { get; set; }
    }
}
