//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificacion
    {
        public Clasificacion()
        {
            this.CabeceraHojasDeRuta = new HashSet<CabeceraHojasDeRuta>();
            this.Contrato = new HashSet<Contrato>();
            this.Contrato1 = new HashSet<Contrato>();
            this.Legajos = new HashSet<Legajos>();
            this.Legajos1 = new HashSet<Legajos>();
            this.Legajos2 = new HashSet<Legajos>();
            this.Legajos3 = new HashSet<Legajos>();
            this.Hijos = new HashSet<Clasificacion>();
            this.Empresa = new HashSet<Empresa>();
            this.Legajos4 = new HashSet<Legajos>();
            this.Contrato2 = new HashSet<Contrato>();
            this.VahiculosyEquipos = new HashSet<VahiculosyEquipos>();
            this.VahiculosyEquipos1 = new HashSet<VahiculosyEquipos>();
            this.VehiculosYPF = new HashSet<VehiculosYPF>();
            this.VehiculosYPF1 = new HashSet<VehiculosYPF>();
            this.VehiculosYPF2 = new HashSet<VehiculosYPF>();
            this.VehiculosYPF3 = new HashSet<VehiculosYPF>();
            this.SeguimientoAuditoria = new HashSet<SeguimientoAuditoria>();
            this.SeguimientoAuditoria1 = new HashSet<SeguimientoAuditoria>();
            this.VehiculosYPF2_1 = new HashSet<VehiculosYPF>();
            this.VehiculosYPF5 = new HashSet<VehiculosYPF>();
            this.SeguimientoAuditoria11 = new HashSet<SeguimientoAuditoria>();
        }
    
        public long IdClasificacion { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<CabeceraHojasDeRuta> CabeceraHojasDeRuta { get; set; }
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<Contrato> Contrato1 { get; set; }
        public virtual ICollection<Legajos> Legajos { get; set; }
        public virtual ICollection<Legajos> Legajos1 { get; set; }
        public virtual ICollection<Legajos> Legajos2 { get; set; }
        public virtual ICollection<Legajos> Legajos3 { get; set; }
        public virtual ICollection<Clasificacion> Hijos { get; set; }
        public virtual Clasificacion Padre { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Legajos> Legajos4 { get; set; }
        public virtual ICollection<Contrato> Contrato2 { get; set; }
        public virtual ICollection<VahiculosyEquipos> VahiculosyEquipos { get; set; }
        public virtual ICollection<VahiculosyEquipos> VahiculosyEquipos1 { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF1 { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF2 { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF3 { get; set; }
        public virtual ICollection<SeguimientoAuditoria> SeguimientoAuditoria { get; set; }
        public virtual ICollection<SeguimientoAuditoria> SeguimientoAuditoria1 { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF2_1 { get; set; }
        public virtual ICollection<VehiculosYPF> VehiculosYPF5 { get; set; }
        public virtual ICollection<SeguimientoAuditoria> SeguimientoAuditoria11 { get; set; }
    }
}
