//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public Contrato()
        {
            this.ContratoEmpresas = new HashSet<ContratoEmpresas>();
            this.DatosDeSueldos = new HashSet<DatosDeSueldos>();
            this.VahiculosyEquipos = new HashSet<VahiculosyEquipos>();
        }
    
        public long IdContrato { get; set; }
        public string Codigo { get; set; }
        public string Servicio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> Prorroga { get; set; }
    
        public virtual Clasificacion TipoContrato { get; set; }
        public virtual Clasificacion Contratadopor { get; set; }
        public virtual ICollection<ContratoEmpresas> ContratoEmpresas { get; set; }
        public virtual ICollection<DatosDeSueldos> DatosDeSueldos { get; set; }
        public virtual Clasificacion objCategoria { get; set; }
        public virtual ICollection<VahiculosyEquipos> VahiculosyEquipos { get; set; }
    }
}
