//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosDeSueldos
    {
        public long IdDatosSueldos { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<decimal> Basico_ValorHora { get; set; }
        public Nullable<decimal> BasicoLiquidado { get; set; }
        public Nullable<decimal> HorasExtras { get; set; }
        public Nullable<decimal> AdicionalesRemunerativos { get; set; }
        public Nullable<decimal> Vacaciones { get; set; }
        public Nullable<decimal> SAC { get; set; }
        public Nullable<decimal> TotalBruto { get; set; }
        public Nullable<decimal> AsignacionFamiliar { get; set; }
        public Nullable<decimal> AdicionalesNORemunerativos { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> TotalNeto { get; set; }
        public string CategoriaCCT { get; set; }
        public string FuncionCCT { get; set; }
    
        public virtual Legajos objLegajo { get; set; }
        public virtual ArchivosSueldos objArchivoSueldo { get; set; }
        public virtual Contrato objContrato { get; set; }
        public virtual Empresa objEmpresa { get; set; }
    }
}
