//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasImp
    {
        public long Id { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<double> CUIT { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Direccion { get; set; }
        public string RepresentanteTecnico { get; set; }
        public string Emergencias { get; set; }
        public string PrestacionEmergencia { get; set; }
        public string CorreoElectronico { get; set; }
        public string ART { get; set; }
    }
}
