//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionPlanTrabajo
    {
        public long IdInfoPlanTrabajo { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> UOCRA { get; set; }
        public Nullable<int> OTROS { get; set; }
        public Nullable<int> INDEPENDIENTES { get; set; }
        public string Contrato { get; set; }
        public string Empresa { get; set; }
    }
}
