//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosEventuales
    {
        public long IdIngresoEventual { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string ApellidoNombre { get; set; }
        public string DNI { get; set; }
        public string Empresa { get; set; }
        public string Contrato { get; set; }
        public string Actividad { get; set; }
        public string Citadopor { get; set; }
        public Nullable<System.DateTime> FechaIngreso1 { get; set; }
        public Nullable<System.DateTime> FechaIngreso2 { get; set; }
        public Nullable<System.DateTime> FechaIngreso3 { get; set; }
        public Nullable<System.DateTime> FechaIngreso4 { get; set; }
        public Nullable<System.DateTime> FechaIngreso5 { get; set; }
    }
}
