//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegajosContratosImp
    {
        public long Id { get; set; }
        public string NroContrato { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Contratista { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Tipo_Documento { get; set; }
        public Nullable<double> NroDoc { get; set; }
        public string FechaNacimiento { get; set; }
        public string CUIL { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string TelefonoFijo { get; set; }
        public string CorreoElectronico { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public string Provincia { get; set; }
        public string Convenio { get; set; }
    }
}
