//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesConosud : DbContext
    {
        public EntidadesConosud()
            : base("name=EntidadesConosud")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ArchivosAdjuntos> ArchivosAdjuntos { get; set; }
        public DbSet<CabeceraHojasDeRuta> CabeceraHojasDeRuta { get; set; }
        public DbSet<CategoriasItems> CategoriasItems { get; set; }
        public DbSet<Clasificacion> Clasificacion { get; set; }
        public DbSet<ContEmpLegajos> ContEmpLegajos { get; set; }
        public DbSet<Contrato> Contrato { get; set; }
        public DbSet<ContratoEmpresas> ContratoEmpresas { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<HojasDeRuta> HojasDeRuta { get; set; }
        public DbSet<Legajos> Legajos { get; set; }
        public DbSet<Plantilla> Plantilla { get; set; }
        public DbSet<RolesPlanilla> RolesPlanilla { get; set; }
        public DbSet<SegMenu> SegMenu { get; set; }
        public DbSet<SegRol> SegRol { get; set; }
        public DbSet<SegRolMenu> SegRolMenu { get; set; }
        public DbSet<SegUsuario> SegUsuario { get; set; }
        public DbSet<SegUsuarioRol> SegUsuarioRol { get; set; }
        public DbSet<ContratosImp> ContratosImp { get; set; }
        public DbSet<LegajosContratosImp> LegajosContratosImp { get; set; }
        public DbSet<EmpresasImp> EmpresasImp { get; set; }
        public DbSet<ComentariosGral> ComentariosGral { get; set; }
        public DbSet<ArchivosSueldos> ArchivosSueldos { get; set; }
        public DbSet<DatosDeSueldos> DatosDeSueldos { get; set; }
        public DbSet<ContratoEmpresasImp> ContratoEmpresasImp { get; set; }
        public DbSet<VahiculosyEquipos> VahiculosyEquipos { get; set; }
        public DbSet<IngresosEventuales> IngresosEventuales { get; set; }
        public DbSet<View_EmpresasContratos> View_EmpresasContratos { get; set; }
        public DbSet<Instructivos> Instructivos { get; set; }
        public DbSet<VehiculosEquiposImp> VehiculosEquiposImp { get; set; }
        public DbSet<ModificacionVehiculos> ModificacionVehiculos { get; set; }
        public DbSet<VehiculosYPF> VehiculosYPF { get; set; }
        public DbSet<InformacionPlanTrabajo> InformacionPlanTrabajo { get; set; }
        public DbSet<CabeceraRutasTransportes> CabeceraRutasTransportes { get; set; }
        public DbSet<RutasTransportes> RutasTransportes { get; set; }
        public DbSet<DomiciliosPersonal> DomiciliosPersonal { get; set; }
        public DbSet<SeguimientoAuditoria> SeguimientoAuditoria { get; set; }
    }
}
