//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutasTransportes
    {
        public long Id { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Departamento { get; set; }
        public Nullable<long> Cabecera { get; set; }
    
        public virtual CabeceraRutasTransportes objCabecera { get; set; }
    }
}
