//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegRol
    {
        public SegRol()
        {
            this.RolesPlanilla = new HashSet<RolesPlanilla>();
            this.SegRolMenu = new HashSet<SegRolMenu>();
            this.SegUsuarioRol = new HashSet<SegUsuarioRol>();
        }
    
        public long IdSegRol { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<RolesPlanilla> RolesPlanilla { get; set; }
        public virtual ICollection<SegRolMenu> SegRolMenu { get; set; }
        public virtual ICollection<SegUsuarioRol> SegUsuarioRol { get; set; }
    }
}
