//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoAuditoria
    {
        public long Id { get; set; }
        public long Cabcera { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<long> AuditorAsignado { get; set; }
        public Nullable<System.DateTime> FechaResultado { get; set; }
        public Nullable<long> Resultado { get; set; }
        public Nullable<System.DateTime> FechaRetencion { get; set; }
        public Nullable<long> Retencion { get; set; }
        public Nullable<System.DateTime> FechaAsignacionInterino { get; set; }
        public Nullable<long> AudtorInterino { get; set; }
        public Nullable<int> NroPresentacion { get; set; }
        public Nullable<bool> Publicado { get; set; }
        public Nullable<long> retencion { get; set; }
    
        public virtual CabeceraHojasDeRuta objCabecera { get; set; }
        public virtual Clasificacion objResultado { get; set; }
        public virtual SegUsuario objAuditorAsignado { get; set; }
        public virtual SegUsuario objAuditorInterino { get; set; }
        public virtual Clasificacion objRetencion { get; set; }
        public virtual Clasificacion Clasificacion1 { get; set; }
    }
}
