//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegUsuario
    {
        public SegUsuario()
        {
            this.SegUsuarioRol = new HashSet<SegUsuarioRol>();
            this.ArchivosSueldos = new HashSet<ArchivosSueldos>();
            this.CabeceraHojasDeRuta = new HashSet<CabeceraHojasDeRuta>();
            this.SeguimientoAuditoria = new HashSet<SeguimientoAuditoria>();
            this.SeguimientoAuditoria1 = new HashSet<SeguimientoAuditoria>();
        }
    
        public long IdSegUsuario { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<SegUsuarioRol> SegUsuarioRol { get; set; }
        public virtual ICollection<ArchivosSueldos> ArchivosSueldos { get; set; }
        public virtual ICollection<CabeceraHojasDeRuta> CabeceraHojasDeRuta { get; set; }
        public virtual ICollection<SeguimientoAuditoria> SeguimientoAuditoria { get; set; }
        public virtual ICollection<SeguimientoAuditoria> SeguimientoAuditoria1 { get; set; }
    }
}
