//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VahiculosyEquipos
    {
        public long IdVehiculoEquipo { get; set; }
        public string Patente { get; set; }
        public Nullable<long> TipoUnidad { get; set; }
        public string NroChasis { get; set; }
        public string CapacidadCarga { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NroMotor { get; set; }
        public string NroHabilitacion { get; set; }
        public Nullable<System.DateTime> FechaHabilitacion { get; set; }
        public Nullable<System.DateTime> FechaVencimientoHabilitacion { get; set; }
        public Nullable<bool> EsPropio { get; set; }
        public string NombreTitular { get; set; }
        public Nullable<System.DateTime> AltaEmpresa { get; set; }
        public Nullable<System.DateTime> BajaEmpresa { get; set; }
        public string EquipamientoAgregado { get; set; }
        public string Tipo { get; set; }
        public Nullable<long> ContratoAfectado { get; set; }
        public Nullable<long> Empresa { get; set; }
        public Nullable<System.DateTime> VencimientoCredencial { get; set; }
        public Nullable<bool> HabilitarCredencial { get; set; }
        public string NroPolizaSeguro { get; set; }
        public string DescripcionSeguro { get; set; }
        public Nullable<long> CompañiaSeguro { get; set; }
        public Nullable<System.DateTime> FechaInicialSeguro { get; set; }
        public Nullable<System.DateTime> FechaVencimientoSeguro { get; set; }
        public Nullable<System.DateTime> FechaUltimoPagoSeguro { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<long> NroInterno { get; set; }
        public string NroHabilitacionEE { get; set; }
        public Nullable<System.DateTime> FechaHabilitacionEE { get; set; }
        public Nullable<System.DateTime> FechaVencimientoHabilitacionEE { get; set; }
        public string PuestoIngreso { get; set; }
    
        public virtual Clasificacion objTipoUnidad { get; set; }
        public virtual Clasificacion objCompañiaSeguro { get; set; }
        public virtual Contrato objContrato { get; set; }
        public virtual Empresa objEmpresa { get; set; }
    }
}
