//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosYPF
    {
        public string Patente { get; set; }
        public string Modelo { get; set; }
        public string Año { get; set; }
        public long Id { get; set; }
        public Nullable<long> Combustible { get; set; }
        public Nullable<long> Departamento { get; set; }
        public Nullable<long> Sector { get; set; }
        public string Titular { get; set; }
        public Nullable<System.DateTime> FechaVtoTarjVerde { get; set; }
        public Nullable<System.DateTime> FechaVtoRevTecnica { get; set; }
        public string Contrato { get; set; }
        public string NroTarjeta { get; set; }
        public Nullable<long> TipoAsignacion { get; set; }
        public string CentroCosto { get; set; }
        public Nullable<System.DateTime> VelocimetroFecha { get; set; }
        public string VelocimetroOdometro { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Observacion { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> TarjetasActivas { get; set; }
        public Nullable<int> LimiteCredito { get; set; }
        public Nullable<int> PIN { get; set; }
        public string TitularPin { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> PIN1 { get; set; }
        public string TitularPin1 { get; set; }
        public Nullable<int> PIN2 { get; set; }
        public string TitularPin2 { get; set; }
        public Nullable<int> PIN3 { get; set; }
        public string TitularPin3 { get; set; }
        public Nullable<int> PIN4 { get; set; }
        public string TitularPin4 { get; set; }
        public Nullable<int> PIN5 { get; set; }
        public string TitularPin5 { get; set; }
        public Nullable<int> PIN6 { get; set; }
        public string TitularPin6 { get; set; }
        public Nullable<int> PIN7 { get; set; }
        public string TitularPin7 { get; set; }
        public string Chasis { get; set; }
        public string Motor { get; set; }
        public Nullable<bool> ABS { get; set; }
        public Nullable<bool> AIRBAGS { get; set; }
        public Nullable<long> Estado { get; set; }
        public Nullable<long> TipoVehiculo { get; set; }
        public Nullable<bool> Llave { get; set; }
        public Nullable<bool> ControlAlarma { get; set; }
        public Nullable<bool> LlaveAlarma { get; set; }
        public string Posicion { get; set; }
        public Nullable<int> LimiteConsMensual { get; set; }
        public Nullable<bool> MICROTRACK { get; set; }
    
        public virtual Clasificacion objTipoCombustible { get; set; }
        public virtual Clasificacion objDepartamento { get; set; }
        public virtual Clasificacion objSector { get; set; }
        public virtual Clasificacion objTipoAsignacion { get; set; }
        public virtual Clasificacion objEstado { get; set; }
        public virtual Clasificacion objTipoVehiculo { get; set; }
    }
}
